package com.auca.quickypay;

import android.os.Bundle;
import android.widget.Button;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.auca.quickypay.Model.Course;
import com.auca.quickypay.sqlite.dbHelper;
import com.google.android.material.textfield.TextInputEditText;

public class AddCourse extends AppCompatActivity {

    private TextInputEditText courseNameEditText, facultyEditText, createdByEditText;
    private Button submitButton;
    private dbHelper dbHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_add_course);

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // Initialize DatabaseHelper
        dbHelper = new dbHelper(this);

        initializeViews();
        setupSubmitButton();
    }

    private void initializeViews() {
        courseNameEditText = findViewById(R.id.courseNameEditText);
        facultyEditText = findViewById(R.id.facultyEditText);
        createdByEditText = findViewById(R.id.createdByEditText);
        submitButton = findViewById(R.id.submitButton);
    }

    private void setupSubmitButton() {
        submitButton.setOnClickListener(v -> {
            if (validateInputs()) {
                createCourse();
            }
        });
    }

    private boolean validateInputs() {
        String courseName = courseNameEditText.getText().toString().trim();
        String facultyIdStr = facultyEditText.getText().toString().trim();
        String createdByStr = createdByEditText.getText().toString().trim();

        if (courseName.isEmpty()) {
            courseNameEditText.setError("Course name is required");
            courseNameEditText.requestFocus();
            return false;
        }

        if (courseName.length() < 2) {
            courseNameEditText.setError("Course name must be at least 2 characters");
            courseNameEditText.requestFocus();
            return false;
        }

        if (facultyIdStr.isEmpty()) {
            facultyEditText.setError("Faculty ID is required");
            facultyEditText.requestFocus();
            return false;
        }

        if (createdByStr.isEmpty()) {
            createdByEditText.setError("Created By is required");
            createdByEditText.requestFocus();
            return false;
        }

        try {
            int facultyId = Integer.parseInt(facultyIdStr);
            if (facultyId <= 0) {
                facultyEditText.setError("Faculty ID must be a positive number");
                facultyEditText.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            facultyEditText.setError("Faculty ID must be a valid number");
            facultyEditText.requestFocus();
            return false;
        }

        try {
            int createdBy = Integer.parseInt(createdByStr);
            if (createdBy <= 0) {
                createdByEditText.setError("Created By must be a positive number");
                createdByEditText.requestFocus();
                return false;
            }
        } catch (NumberFormatException e) {
            createdByEditText.setError("Created By must be a valid number");
            createdByEditText.requestFocus();
            return false;
        }

        return true;
    }

    private void createCourse() {
        String courseName = courseNameEditText.getText().toString().trim();
        int facultyId = Integer.parseInt(facultyEditText.getText().toString().trim());
        int createdBy = Integer.parseInt(createdByEditText.getText().toString().trim());

        // Create Course object
        Course course = new Course(courseName, facultyId, createdBy);

        // Save course to database using your DatabaseHelper
        saveCourse(course);
    }

    private void saveCourse(Course course) {
        long result = dbHelper.addCourse(course);

        if (result != -1) {
            // Success - result contains the courseId generated by database
            String successMessage = String.format(
                    "Course created successfully!\nName: %s\nFaculty ID: %d\nCreated By: %d\nCourse ID: %d",
                    course.getCourseName(),
                    course.getFacultyId(),
                    course.getCreatedBy(),
                    result
            );

            Toast.makeText(this, successMessage, Toast.LENGTH_LONG).show();
            clearForm();

            // Optional: Navigate back or show course list
            // finish();

        } else {
            // Error occurred
            Toast.makeText(this, "Failed to create course. Please try again.", Toast.LENGTH_SHORT).show();
        }
    }

    private void clearForm() {
        courseNameEditText.setText("");
        facultyEditText.setText("");
        createdByEditText.setText("");
        courseNameEditText.requestFocus();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        // Close database connection when activity is destroyed
        if (dbHelper != null) {
           dbHelper.close();
        }
    }
}